//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SopSistemiEntities1 : DbContext
    {
        public SopSistemiEntities1()
            : base("name=SopSistemiEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sopKayit> sopKayit { get; set; }
        public virtual DbSet<sopOnay> sopOnay { get; set; }
        public virtual DbSet<sopUser> sopUser { get; set; }
    }
}
