//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sopKayit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sopKayit()
        {
            this.sopOnay = new HashSet<sopOnay>();
        }
    
        public int sopID { get; set; }
        public string baslik { get; set; }
        public string dosya { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
    
        public virtual sopUser sopUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sopOnay> sopOnay { get; set; }
    }
}
